/*
 * generated by Xtext 2.10.0
 */
package uo.diesels.model.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import uo.diesels.model.ide.contentassist.antlr.internal.InternalPersistenceDslParser;
import uo.diesels.model.services.PersistenceDslGrammarAccess;

public class PersistenceDslParser extends AbstractContentAssistParser {

	@Inject
	private PersistenceDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalPersistenceDslParser createParser() {
		InternalPersistenceDslParser result = new InternalPersistenceDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getFinderMethodAccess().getAlternatives(), "rule__FinderMethod__Alternatives");
					put(grammarAccess.getCollectionReturnTypeAccess().getAlternatives(), "rule__CollectionReturnType__Alternatives");
					put(grammarAccess.getAllModelTypeCollectionAccess().getCollectionAlternatives_0_0(), "rule__AllModelTypeCollection__CollectionAlternatives_0_0");
					put(grammarAccess.getSimpleTypeCollectionAccess().getCollectionAlternatives_0_0(), "rule__SimpleTypeCollection__CollectionAlternatives_0_0");
					put(grammarAccess.getDefVariableAccess().getAlternatives(), "rule__DefVariable__Alternatives");
					put(grammarAccess.getDefCollectionTypeVariableAccess().getAlternatives(), "rule__DefCollectionTypeVariable__Alternatives");
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getBasicTypeAccess().getAlternatives(), "rule__BasicType__Alternatives");
					put(grammarAccess.getFinderAccess().getGroup(), "rule__Finder__Group__0");
					put(grammarAccess.getMethodSimpleReturnAccess().getGroup(), "rule__MethodSimpleReturn__Group__0");
					put(grammarAccess.getMethodSimpleReturnAccess().getGroup_3(), "rule__MethodSimpleReturn__Group_3__0");
					put(grammarAccess.getMethodSimpleReturnAccess().getGroup_3_1(), "rule__MethodSimpleReturn__Group_3_1__0");
					put(grammarAccess.getMethodEntityReturnAccess().getGroup(), "rule__MethodEntityReturn__Group__0");
					put(grammarAccess.getMethodEntityReturnAccess().getGroup_3(), "rule__MethodEntityReturn__Group_3__0");
					put(grammarAccess.getMethodEntityReturnAccess().getGroup_3_1(), "rule__MethodEntityReturn__Group_3_1__0");
					put(grammarAccess.getMethodDtoReturnAccess().getGroup(), "rule__MethodDtoReturn__Group__0");
					put(grammarAccess.getMethodDtoReturnAccess().getGroup_4(), "rule__MethodDtoReturn__Group_4__0");
					put(grammarAccess.getMethodDtoReturnAccess().getGroup_4_1(), "rule__MethodDtoReturn__Group_4_1__0");
					put(grammarAccess.getMethodCollectionReturnAccess().getGroup(), "rule__MethodCollectionReturn__Group__0");
					put(grammarAccess.getMethodCollectionReturnAccess().getGroup_3(), "rule__MethodCollectionReturn__Group_3__0");
					put(grammarAccess.getMethodCollectionReturnAccess().getGroup_3_1(), "rule__MethodCollectionReturn__Group_3_1__0");
					put(grammarAccess.getEntityReturnTypeCollectionAccess().getGroup(), "rule__EntityReturnTypeCollection__Group__0");
					put(grammarAccess.getDtoReturnTypeCollectionAccess().getGroup(), "rule__DtoReturnTypeCollection__Group__0");
					put(grammarAccess.getSimpleReturnTypeCollectionAccess().getGroup(), "rule__SimpleReturnTypeCollection__Group__0");
					put(grammarAccess.getAllModelTypeCollectionAccess().getGroup(), "rule__AllModelTypeCollection__Group__0");
					put(grammarAccess.getSimpleTypeCollectionAccess().getGroup(), "rule__SimpleTypeCollection__Group__0");
					put(grammarAccess.getDefAllModelTypeVariableAccess().getGroup(), "rule__DefAllModelTypeVariable__Group__0");
					put(grammarAccess.getDefSimpleVariableAccess().getGroup(), "rule__DefSimpleVariable__Group__0");
					put(grammarAccess.getDefAllModelTypeCollectionVariableAccess().getGroup(), "rule__DefAllModelTypeCollectionVariable__Group__0");
					put(grammarAccess.getDefSimpleTypeCollectionVariableAccess().getGroup(), "rule__DefSimpleTypeCollectionVariable__Group__0");
					put(grammarAccess.getModelAccess().getFinderAssignment(), "rule__Model__FinderAssignment");
					put(grammarAccess.getFinderAccess().getNameAssignment_1(), "rule__Finder__NameAssignment_1");
					put(grammarAccess.getFinderAccess().getMethodsAssignment_3(), "rule__Finder__MethodsAssignment_3");
					put(grammarAccess.getMethodSimpleReturnAccess().getReturnTypeAssignment_0(), "rule__MethodSimpleReturn__ReturnTypeAssignment_0");
					put(grammarAccess.getMethodSimpleReturnAccess().getNameAssignment_1(), "rule__MethodSimpleReturn__NameAssignment_1");
					put(grammarAccess.getMethodSimpleReturnAccess().getParametersAssignment_3_0(), "rule__MethodSimpleReturn__ParametersAssignment_3_0");
					put(grammarAccess.getMethodSimpleReturnAccess().getParametersAssignment_3_1_1(), "rule__MethodSimpleReturn__ParametersAssignment_3_1_1");
					put(grammarAccess.getMethodSimpleReturnAccess().getNullableAssignment_5(), "rule__MethodSimpleReturn__NullableAssignment_5");
					put(grammarAccess.getMethodEntityReturnAccess().getReturnTypeAssignment_0(), "rule__MethodEntityReturn__ReturnTypeAssignment_0");
					put(grammarAccess.getMethodEntityReturnAccess().getNameAssignment_1(), "rule__MethodEntityReturn__NameAssignment_1");
					put(grammarAccess.getMethodEntityReturnAccess().getParametersAssignment_3_0(), "rule__MethodEntityReturn__ParametersAssignment_3_0");
					put(grammarAccess.getMethodEntityReturnAccess().getParametersAssignment_3_1_1(), "rule__MethodEntityReturn__ParametersAssignment_3_1_1");
					put(grammarAccess.getMethodEntityReturnAccess().getNullableAssignment_5(), "rule__MethodEntityReturn__NullableAssignment_5");
					put(grammarAccess.getMethodDtoReturnAccess().getReturnTypeAssignment_1(), "rule__MethodDtoReturn__ReturnTypeAssignment_1");
					put(grammarAccess.getMethodDtoReturnAccess().getNameAssignment_2(), "rule__MethodDtoReturn__NameAssignment_2");
					put(grammarAccess.getMethodDtoReturnAccess().getParametersAssignment_4_0(), "rule__MethodDtoReturn__ParametersAssignment_4_0");
					put(grammarAccess.getMethodDtoReturnAccess().getParametersAssignment_4_1_1(), "rule__MethodDtoReturn__ParametersAssignment_4_1_1");
					put(grammarAccess.getMethodDtoReturnAccess().getNullableAssignment_6(), "rule__MethodDtoReturn__NullableAssignment_6");
					put(grammarAccess.getMethodCollectionReturnAccess().getReturnTypeAssignment_0(), "rule__MethodCollectionReturn__ReturnTypeAssignment_0");
					put(grammarAccess.getMethodCollectionReturnAccess().getNameAssignment_1(), "rule__MethodCollectionReturn__NameAssignment_1");
					put(grammarAccess.getMethodCollectionReturnAccess().getParametersAssignment_3_0(), "rule__MethodCollectionReturn__ParametersAssignment_3_0");
					put(grammarAccess.getMethodCollectionReturnAccess().getParametersAssignment_3_1_1(), "rule__MethodCollectionReturn__ParametersAssignment_3_1_1");
					put(grammarAccess.getEntityReturnTypeCollectionAccess().getTypeAssignment_2(), "rule__EntityReturnTypeCollection__TypeAssignment_2");
					put(grammarAccess.getDtoReturnTypeCollectionAccess().getTypeAssignment_3(), "rule__DtoReturnTypeCollection__TypeAssignment_3");
					put(grammarAccess.getSimpleReturnTypeCollectionAccess().getTypeAssignment_2(), "rule__SimpleReturnTypeCollection__TypeAssignment_2");
					put(grammarAccess.getAllModelTypeCollectionAccess().getCollectionAssignment_0(), "rule__AllModelTypeCollection__CollectionAssignment_0");
					put(grammarAccess.getAllModelTypeCollectionAccess().getTypeAssignment_2(), "rule__AllModelTypeCollection__TypeAssignment_2");
					put(grammarAccess.getSimpleTypeCollectionAccess().getCollectionAssignment_0(), "rule__SimpleTypeCollection__CollectionAssignment_0");
					put(grammarAccess.getSimpleTypeCollectionAccess().getTypeAssignment_2(), "rule__SimpleTypeCollection__TypeAssignment_2");
					put(grammarAccess.getDefAllModelTypeVariableAccess().getTypeAssignment_0(), "rule__DefAllModelTypeVariable__TypeAssignment_0");
					put(grammarAccess.getDefAllModelTypeVariableAccess().getNameAssignment_1(), "rule__DefAllModelTypeVariable__NameAssignment_1");
					put(grammarAccess.getDefSimpleVariableAccess().getTypeAssignment_0(), "rule__DefSimpleVariable__TypeAssignment_0");
					put(grammarAccess.getDefSimpleVariableAccess().getNameAssignment_1(), "rule__DefSimpleVariable__NameAssignment_1");
					put(grammarAccess.getDefAllModelTypeCollectionVariableAccess().getTypeAssignment_0(), "rule__DefAllModelTypeCollectionVariable__TypeAssignment_0");
					put(grammarAccess.getDefAllModelTypeCollectionVariableAccess().getNameAssignment_1(), "rule__DefAllModelTypeCollectionVariable__NameAssignment_1");
					put(grammarAccess.getDefSimpleTypeCollectionVariableAccess().getTypeAssignment_0(), "rule__DefSimpleTypeCollectionVariable__TypeAssignment_0");
					put(grammarAccess.getDefSimpleTypeCollectionVariableAccess().getNameAssignment_1(), "rule__DefSimpleTypeCollectionVariable__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalPersistenceDslParser typedParser = (InternalPersistenceDslParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public PersistenceDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PersistenceDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
