/*
 * generated by Xtext 2.9.0
 */
package uo.diesels.model


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BusinessDslStandaloneSetup extends BusinessDslStandaloneSetupGenerated {

	def static void doSetup() {
		new BusinessDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
