/*
 * generated by Xtext 2.9.0
 */
package uo.diesels.model


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ModelDslRuntimeModule extends AbstractModelDslRuntimeModule {
}
