/*
 * generated by Xtext 2.9.0
 */
package uo.diesels.model


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PersistenceDslStandaloneSetup extends PersistenceDslStandaloneSetupGenerated {

	def static void doSetup() {
		new PersistenceDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
