/*
 * generated by Xtext 2.9.0
 */
package uo.diesels.model.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DtoDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("uo/diesels/model/parser/antlr/internal/InternalDtoDsl.tokens");
	}
}
