/**
 * generated by Xtext 2.9.0
 */
package uo.diesels.model.modelDsl.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import uo.diesels.model.modelDsl.AllModelType;
import uo.diesels.model.modelDsl.AllModelTypeCollection;
import uo.diesels.model.modelDsl.AssociativeEntity;
import uo.diesels.model.modelDsl.CollectionReturnType;
import uo.diesels.model.modelDsl.DefAllModelTypeVariable;
import uo.diesels.model.modelDsl.DefAttribute;
import uo.diesels.model.modelDsl.DefCollectionTypeAttribute;
import uo.diesels.model.modelDsl.DefCollectionTypeVariable;
import uo.diesels.model.modelDsl.DefIdAttribute;
import uo.diesels.model.modelDsl.DefLinkVariable;
import uo.diesels.model.modelDsl.DefModelModelTypeCollectionVariable;
import uo.diesels.model.modelDsl.DefModelSimpleTypeCollectionVariable;
import uo.diesels.model.modelDsl.DefModelTypeVariable;
import uo.diesels.model.modelDsl.DefSimpleVariable;
import uo.diesels.model.modelDsl.DefVariable;
import uo.diesels.model.modelDsl.Element;
import uo.diesels.model.modelDsl.Entity;
import uo.diesels.model.modelDsl.Enumerable;
import uo.diesels.model.modelDsl.Link;
import uo.diesels.model.modelDsl.Method;
import uo.diesels.model.modelDsl.MethodAllModelReturn;
import uo.diesels.model.modelDsl.MethodCollectionReturn;
import uo.diesels.model.modelDsl.MethodSimpleReturn;
import uo.diesels.model.modelDsl.Model;
import uo.diesels.model.modelDsl.ModelDslFactory;
import uo.diesels.model.modelDsl.ModelDslPackage;
import uo.diesels.model.modelDsl.ModelType;
import uo.diesels.model.modelDsl.ModelTypeCollection;
import uo.diesels.model.modelDsl.Relation;
import uo.diesels.model.modelDsl.SimpleEntity;
import uo.diesels.model.modelDsl.SimpleLink;
import uo.diesels.model.modelDsl.SimpleTypeCollection;
import uo.diesels.model.modelDsl.ValueType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ModelDslPackageImpl extends EPackageImpl implements ModelDslPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass allModelTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass linkEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass simpleEntityEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass associativeEntityEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass valueTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass enumerableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass simpleLinkEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass relationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass defAttributeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass defVariableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass defIdAttributeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass defAllModelTypeVariableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass defSimpleVariableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass defModelTypeVariableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass defCollectionTypeAttributeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass defCollectionTypeVariableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass defModelModelTypeCollectionVariableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass defModelSimpleTypeCollectionVariableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass defLinkVariableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass methodEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass methodSimpleReturnEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass methodCollectionReturnEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass methodAllModelReturnEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass allModelTypeCollectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelTypeCollectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass simpleTypeCollectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass collectionReturnTypeEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see uo.diesels.model.modelDsl.ModelDslPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private ModelDslPackageImpl()
  {
    super(eNS_URI, ModelDslFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link ModelDslPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static ModelDslPackage init()
  {
    if (isInited) return (ModelDslPackage)EPackage.Registry.INSTANCE.getEPackage(ModelDslPackage.eNS_URI);

    // Obtain or create and register package
    ModelDslPackageImpl theModelDslPackage = (ModelDslPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof ModelDslPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new ModelDslPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theModelDslPackage.createPackageContents();

    // Initialize created meta-data
    theModelDslPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theModelDslPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(ModelDslPackage.eNS_URI, theModelDslPackage);
    return theModelDslPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getModel_Elements()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getElement()
  {
    return elementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getElement_Name()
  {
    return (EAttribute)elementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAllModelType()
  {
    return allModelTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntity()
  {
    return entityEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntity_Attributes()
  {
    return (EReference)entityEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntity_Methods()
  {
    return (EReference)entityEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModelType()
  {
    return modelTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getLink()
  {
    return linkEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSimpleEntity()
  {
    return simpleEntityEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSimpleEntity_Implementation()
  {
    return (EAttribute)simpleEntityEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSimpleEntity_SuperClass()
  {
    return (EReference)simpleEntityEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSimpleEntity_AttributesId()
  {
    return (EReference)simpleEntityEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAssociativeEntity()
  {
    return associativeEntityEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAssociativeEntity_Relations()
  {
    return (EReference)associativeEntityEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getValueType()
  {
    return valueTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getValueType_Attributes()
  {
    return (EReference)valueTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEnumerable()
  {
    return enumerableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEnumerable_Enums()
  {
    return (EAttribute)enumerableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSimpleLink()
  {
    return simpleLinkEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSimpleLink_Relations()
  {
    return (EReference)simpleLinkEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRelation()
  {
    return relationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRelation_Multiplicity()
  {
    return (EAttribute)relationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRelation_Type()
  {
    return (EReference)relationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRelation_Name()
  {
    return (EAttribute)relationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRelation_Navigable()
  {
    return (EAttribute)relationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDefAttribute()
  {
    return defAttributeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDefVariable()
  {
    return defVariableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDefVariable_Name()
  {
    return (EAttribute)defVariableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDefIdAttribute()
  {
    return defIdAttributeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDefAllModelTypeVariable()
  {
    return defAllModelTypeVariableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDefAllModelTypeVariable_Type()
  {
    return (EReference)defAllModelTypeVariableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDefSimpleVariable()
  {
    return defSimpleVariableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDefSimpleVariable_Nullable()
  {
    return (EAttribute)defSimpleVariableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDefSimpleVariable_Type()
  {
    return (EAttribute)defSimpleVariableEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDefModelTypeVariable()
  {
    return defModelTypeVariableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDefModelTypeVariable_Nullable()
  {
    return (EAttribute)defModelTypeVariableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDefModelTypeVariable_Type()
  {
    return (EReference)defModelTypeVariableEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDefModelTypeVariable_Name()
  {
    return (EAttribute)defModelTypeVariableEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDefCollectionTypeAttribute()
  {
    return defCollectionTypeAttributeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDefCollectionTypeAttribute_Name()
  {
    return (EAttribute)defCollectionTypeAttributeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDefCollectionTypeVariable()
  {
    return defCollectionTypeVariableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDefCollectionTypeVariable_Type()
  {
    return (EReference)defCollectionTypeVariableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDefModelModelTypeCollectionVariable()
  {
    return defModelModelTypeCollectionVariableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDefModelModelTypeCollectionVariable_Type()
  {
    return (EReference)defModelModelTypeCollectionVariableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDefModelSimpleTypeCollectionVariable()
  {
    return defModelSimpleTypeCollectionVariableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDefModelSimpleTypeCollectionVariable_Type()
  {
    return (EReference)defModelSimpleTypeCollectionVariableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDefLinkVariable()
  {
    return defLinkVariableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDefLinkVariable_Type()
  {
    return (EReference)defLinkVariableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDefLinkVariable_Name()
  {
    return (EAttribute)defLinkVariableEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMethod()
  {
    return methodEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMethod_Name()
  {
    return (EAttribute)methodEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMethod_Parameters()
  {
    return (EReference)methodEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMethodSimpleReturn()
  {
    return methodSimpleReturnEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMethodSimpleReturn_ReturnType()
  {
    return (EAttribute)methodSimpleReturnEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMethodCollectionReturn()
  {
    return methodCollectionReturnEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMethodCollectionReturn_ReturnType()
  {
    return (EReference)methodCollectionReturnEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMethodAllModelReturn()
  {
    return methodAllModelReturnEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMethodAllModelReturn_ReturnType()
  {
    return (EReference)methodAllModelReturnEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAllModelTypeCollection()
  {
    return allModelTypeCollectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAllModelTypeCollection_Type()
  {
    return (EReference)allModelTypeCollectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModelTypeCollection()
  {
    return modelTypeCollectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getModelTypeCollection_Collection()
  {
    return (EAttribute)modelTypeCollectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getModelTypeCollection_Type()
  {
    return (EReference)modelTypeCollectionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSimpleTypeCollection()
  {
    return simpleTypeCollectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSimpleTypeCollection_Type()
  {
    return (EAttribute)simpleTypeCollectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCollectionReturnType()
  {
    return collectionReturnTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCollectionReturnType_Collection()
  {
    return (EAttribute)collectionReturnTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ModelDslFactory getModelDslFactory()
  {
    return (ModelDslFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__ELEMENTS);

    elementEClass = createEClass(ELEMENT);
    createEAttribute(elementEClass, ELEMENT__NAME);

    allModelTypeEClass = createEClass(ALL_MODEL_TYPE);

    entityEClass = createEClass(ENTITY);
    createEReference(entityEClass, ENTITY__ATTRIBUTES);
    createEReference(entityEClass, ENTITY__METHODS);

    modelTypeEClass = createEClass(MODEL_TYPE);

    linkEClass = createEClass(LINK);

    simpleEntityEClass = createEClass(SIMPLE_ENTITY);
    createEAttribute(simpleEntityEClass, SIMPLE_ENTITY__IMPLEMENTATION);
    createEReference(simpleEntityEClass, SIMPLE_ENTITY__SUPER_CLASS);
    createEReference(simpleEntityEClass, SIMPLE_ENTITY__ATTRIBUTES_ID);

    associativeEntityEClass = createEClass(ASSOCIATIVE_ENTITY);
    createEReference(associativeEntityEClass, ASSOCIATIVE_ENTITY__RELATIONS);

    valueTypeEClass = createEClass(VALUE_TYPE);
    createEReference(valueTypeEClass, VALUE_TYPE__ATTRIBUTES);

    enumerableEClass = createEClass(ENUMERABLE);
    createEAttribute(enumerableEClass, ENUMERABLE__ENUMS);

    simpleLinkEClass = createEClass(SIMPLE_LINK);
    createEReference(simpleLinkEClass, SIMPLE_LINK__RELATIONS);

    relationEClass = createEClass(RELATION);
    createEAttribute(relationEClass, RELATION__MULTIPLICITY);
    createEReference(relationEClass, RELATION__TYPE);
    createEAttribute(relationEClass, RELATION__NAME);
    createEAttribute(relationEClass, RELATION__NAVIGABLE);

    defAttributeEClass = createEClass(DEF_ATTRIBUTE);

    defVariableEClass = createEClass(DEF_VARIABLE);
    createEAttribute(defVariableEClass, DEF_VARIABLE__NAME);

    defIdAttributeEClass = createEClass(DEF_ID_ATTRIBUTE);

    defAllModelTypeVariableEClass = createEClass(DEF_ALL_MODEL_TYPE_VARIABLE);
    createEReference(defAllModelTypeVariableEClass, DEF_ALL_MODEL_TYPE_VARIABLE__TYPE);

    defSimpleVariableEClass = createEClass(DEF_SIMPLE_VARIABLE);
    createEAttribute(defSimpleVariableEClass, DEF_SIMPLE_VARIABLE__NULLABLE);
    createEAttribute(defSimpleVariableEClass, DEF_SIMPLE_VARIABLE__TYPE);

    defModelTypeVariableEClass = createEClass(DEF_MODEL_TYPE_VARIABLE);
    createEAttribute(defModelTypeVariableEClass, DEF_MODEL_TYPE_VARIABLE__NULLABLE);
    createEReference(defModelTypeVariableEClass, DEF_MODEL_TYPE_VARIABLE__TYPE);
    createEAttribute(defModelTypeVariableEClass, DEF_MODEL_TYPE_VARIABLE__NAME);

    defCollectionTypeAttributeEClass = createEClass(DEF_COLLECTION_TYPE_ATTRIBUTE);
    createEAttribute(defCollectionTypeAttributeEClass, DEF_COLLECTION_TYPE_ATTRIBUTE__NAME);

    defCollectionTypeVariableEClass = createEClass(DEF_COLLECTION_TYPE_VARIABLE);
    createEReference(defCollectionTypeVariableEClass, DEF_COLLECTION_TYPE_VARIABLE__TYPE);

    defModelModelTypeCollectionVariableEClass = createEClass(DEF_MODEL_MODEL_TYPE_COLLECTION_VARIABLE);
    createEReference(defModelModelTypeCollectionVariableEClass, DEF_MODEL_MODEL_TYPE_COLLECTION_VARIABLE__TYPE);

    defModelSimpleTypeCollectionVariableEClass = createEClass(DEF_MODEL_SIMPLE_TYPE_COLLECTION_VARIABLE);
    createEReference(defModelSimpleTypeCollectionVariableEClass, DEF_MODEL_SIMPLE_TYPE_COLLECTION_VARIABLE__TYPE);

    defLinkVariableEClass = createEClass(DEF_LINK_VARIABLE);
    createEReference(defLinkVariableEClass, DEF_LINK_VARIABLE__TYPE);
    createEAttribute(defLinkVariableEClass, DEF_LINK_VARIABLE__NAME);

    methodEClass = createEClass(METHOD);
    createEAttribute(methodEClass, METHOD__NAME);
    createEReference(methodEClass, METHOD__PARAMETERS);

    methodSimpleReturnEClass = createEClass(METHOD_SIMPLE_RETURN);
    createEAttribute(methodSimpleReturnEClass, METHOD_SIMPLE_RETURN__RETURN_TYPE);

    methodCollectionReturnEClass = createEClass(METHOD_COLLECTION_RETURN);
    createEReference(methodCollectionReturnEClass, METHOD_COLLECTION_RETURN__RETURN_TYPE);

    methodAllModelReturnEClass = createEClass(METHOD_ALL_MODEL_RETURN);
    createEReference(methodAllModelReturnEClass, METHOD_ALL_MODEL_RETURN__RETURN_TYPE);

    allModelTypeCollectionEClass = createEClass(ALL_MODEL_TYPE_COLLECTION);
    createEReference(allModelTypeCollectionEClass, ALL_MODEL_TYPE_COLLECTION__TYPE);

    modelTypeCollectionEClass = createEClass(MODEL_TYPE_COLLECTION);
    createEAttribute(modelTypeCollectionEClass, MODEL_TYPE_COLLECTION__COLLECTION);
    createEReference(modelTypeCollectionEClass, MODEL_TYPE_COLLECTION__TYPE);

    simpleTypeCollectionEClass = createEClass(SIMPLE_TYPE_COLLECTION);
    createEAttribute(simpleTypeCollectionEClass, SIMPLE_TYPE_COLLECTION__TYPE);

    collectionReturnTypeEClass = createEClass(COLLECTION_RETURN_TYPE);
    createEAttribute(collectionReturnTypeEClass, COLLECTION_RETURN_TYPE__COLLECTION);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    allModelTypeEClass.getESuperTypes().add(this.getElement());
    entityEClass.getESuperTypes().add(this.getAllModelType());
    modelTypeEClass.getESuperTypes().add(this.getAllModelType());
    simpleEntityEClass.getESuperTypes().add(this.getEntity());
    associativeEntityEClass.getESuperTypes().add(this.getEntity());
    associativeEntityEClass.getESuperTypes().add(this.getLink());
    valueTypeEClass.getESuperTypes().add(this.getModelType());
    enumerableEClass.getESuperTypes().add(this.getModelType());
    simpleLinkEClass.getESuperTypes().add(this.getElement());
    simpleLinkEClass.getESuperTypes().add(this.getLink());
    defAllModelTypeVariableEClass.getESuperTypes().add(this.getDefVariable());
    defSimpleVariableEClass.getESuperTypes().add(this.getDefAttribute());
    defSimpleVariableEClass.getESuperTypes().add(this.getDefVariable());
    defSimpleVariableEClass.getESuperTypes().add(this.getDefIdAttribute());
    defModelTypeVariableEClass.getESuperTypes().add(this.getDefAttribute());
    defModelTypeVariableEClass.getESuperTypes().add(this.getDefIdAttribute());
    defCollectionTypeAttributeEClass.getESuperTypes().add(this.getDefAttribute());
    defCollectionTypeVariableEClass.getESuperTypes().add(this.getDefVariable());
    defModelModelTypeCollectionVariableEClass.getESuperTypes().add(this.getDefCollectionTypeAttribute());
    defModelSimpleTypeCollectionVariableEClass.getESuperTypes().add(this.getDefCollectionTypeAttribute());
    defLinkVariableEClass.getESuperTypes().add(this.getDefIdAttribute());
    methodSimpleReturnEClass.getESuperTypes().add(this.getMethod());
    methodCollectionReturnEClass.getESuperTypes().add(this.getMethod());
    methodAllModelReturnEClass.getESuperTypes().add(this.getMethod());
    allModelTypeCollectionEClass.getESuperTypes().add(this.getCollectionReturnType());
    simpleTypeCollectionEClass.getESuperTypes().add(this.getCollectionReturnType());

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Elements(), this.getElement(), null, "elements", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(elementEClass, Element.class, "Element", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getElement_Name(), ecorePackage.getEString(), "name", null, 0, 1, Element.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(allModelTypeEClass, AllModelType.class, "AllModelType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(entityEClass, Entity.class, "Entity", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEntity_Attributes(), this.getDefAttribute(), null, "attributes", null, 0, -1, Entity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntity_Methods(), this.getMethod(), null, "methods", null, 0, -1, Entity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(modelTypeEClass, ModelType.class, "ModelType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(linkEClass, Link.class, "Link", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(simpleEntityEClass, SimpleEntity.class, "SimpleEntity", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSimpleEntity_Implementation(), ecorePackage.getEString(), "implementation", null, 0, 1, SimpleEntity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSimpleEntity_SuperClass(), this.getSimpleEntity(), null, "superClass", null, 0, 1, SimpleEntity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSimpleEntity_AttributesId(), this.getDefIdAttribute(), null, "attributesId", null, 0, -1, SimpleEntity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(associativeEntityEClass, AssociativeEntity.class, "AssociativeEntity", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAssociativeEntity_Relations(), this.getRelation(), null, "relations", null, 0, -1, AssociativeEntity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(valueTypeEClass, ValueType.class, "ValueType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getValueType_Attributes(), this.getDefAttribute(), null, "attributes", null, 0, -1, ValueType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(enumerableEClass, Enumerable.class, "Enumerable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEnumerable_Enums(), ecorePackage.getEString(), "enums", null, 0, -1, Enumerable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(simpleLinkEClass, SimpleLink.class, "SimpleLink", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSimpleLink_Relations(), this.getRelation(), null, "relations", null, 0, -1, SimpleLink.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(relationEClass, Relation.class, "Relation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRelation_Multiplicity(), ecorePackage.getEString(), "multiplicity", null, 0, 1, Relation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRelation_Type(), this.getEntity(), null, "type", null, 0, 1, Relation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRelation_Name(), ecorePackage.getEString(), "name", null, 0, 1, Relation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRelation_Navigable(), ecorePackage.getEString(), "navigable", null, 0, 1, Relation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(defAttributeEClass, DefAttribute.class, "DefAttribute", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(defVariableEClass, DefVariable.class, "DefVariable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDefVariable_Name(), ecorePackage.getEString(), "name", null, 0, 1, DefVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(defIdAttributeEClass, DefIdAttribute.class, "DefIdAttribute", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(defAllModelTypeVariableEClass, DefAllModelTypeVariable.class, "DefAllModelTypeVariable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDefAllModelTypeVariable_Type(), this.getAllModelType(), null, "type", null, 0, 1, DefAllModelTypeVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(defSimpleVariableEClass, DefSimpleVariable.class, "DefSimpleVariable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDefSimpleVariable_Nullable(), ecorePackage.getEString(), "nullable", null, 0, 1, DefSimpleVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDefSimpleVariable_Type(), ecorePackage.getEString(), "type", null, 0, 1, DefSimpleVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(defModelTypeVariableEClass, DefModelTypeVariable.class, "DefModelTypeVariable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDefModelTypeVariable_Nullable(), ecorePackage.getEString(), "nullable", null, 0, 1, DefModelTypeVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDefModelTypeVariable_Type(), this.getModelType(), null, "type", null, 0, 1, DefModelTypeVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDefModelTypeVariable_Name(), ecorePackage.getEString(), "name", null, 0, 1, DefModelTypeVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(defCollectionTypeAttributeEClass, DefCollectionTypeAttribute.class, "DefCollectionTypeAttribute", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDefCollectionTypeAttribute_Name(), ecorePackage.getEString(), "name", null, 0, 1, DefCollectionTypeAttribute.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(defCollectionTypeVariableEClass, DefCollectionTypeVariable.class, "DefCollectionTypeVariable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDefCollectionTypeVariable_Type(), this.getCollectionReturnType(), null, "type", null, 0, 1, DefCollectionTypeVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(defModelModelTypeCollectionVariableEClass, DefModelModelTypeCollectionVariable.class, "DefModelModelTypeCollectionVariable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDefModelModelTypeCollectionVariable_Type(), this.getModelTypeCollection(), null, "type", null, 0, 1, DefModelModelTypeCollectionVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(defModelSimpleTypeCollectionVariableEClass, DefModelSimpleTypeCollectionVariable.class, "DefModelSimpleTypeCollectionVariable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDefModelSimpleTypeCollectionVariable_Type(), this.getSimpleTypeCollection(), null, "type", null, 0, 1, DefModelSimpleTypeCollectionVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(defLinkVariableEClass, DefLinkVariable.class, "DefLinkVariable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDefLinkVariable_Type(), this.getLink(), null, "type", null, 0, 1, DefLinkVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDefLinkVariable_Name(), ecorePackage.getEString(), "name", null, 0, 1, DefLinkVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(methodEClass, Method.class, "Method", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMethod_Name(), ecorePackage.getEString(), "name", null, 0, 1, Method.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMethod_Parameters(), this.getDefVariable(), null, "parameters", null, 0, -1, Method.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(methodSimpleReturnEClass, MethodSimpleReturn.class, "MethodSimpleReturn", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMethodSimpleReturn_ReturnType(), ecorePackage.getEString(), "returnType", null, 0, 1, MethodSimpleReturn.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(methodCollectionReturnEClass, MethodCollectionReturn.class, "MethodCollectionReturn", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMethodCollectionReturn_ReturnType(), this.getCollectionReturnType(), null, "returnType", null, 0, 1, MethodCollectionReturn.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(methodAllModelReturnEClass, MethodAllModelReturn.class, "MethodAllModelReturn", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMethodAllModelReturn_ReturnType(), this.getAllModelType(), null, "returnType", null, 0, 1, MethodAllModelReturn.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(allModelTypeCollectionEClass, AllModelTypeCollection.class, "AllModelTypeCollection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAllModelTypeCollection_Type(), this.getAllModelType(), null, "type", null, 0, 1, AllModelTypeCollection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(modelTypeCollectionEClass, ModelTypeCollection.class, "ModelTypeCollection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getModelTypeCollection_Collection(), ecorePackage.getEString(), "collection", null, 0, 1, ModelTypeCollection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModelTypeCollection_Type(), this.getModelType(), null, "type", null, 0, 1, ModelTypeCollection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(simpleTypeCollectionEClass, SimpleTypeCollection.class, "SimpleTypeCollection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSimpleTypeCollection_Type(), ecorePackage.getEString(), "type", null, 0, 1, SimpleTypeCollection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(collectionReturnTypeEClass, CollectionReturnType.class, "CollectionReturnType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCollectionReturnType_Collection(), ecorePackage.getEString(), "collection", null, 0, 1, CollectionReturnType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //ModelDslPackageImpl
