/**
 * generated by Xtext 2.10.0
 */
package uo.diesels.model.persistenceDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Def Collection Type Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uo.diesels.model.persistenceDsl.PersistenceDslPackage#getDefCollectionTypeVariable()
 * @model
 * @generated
 */
public interface DefCollectionTypeVariable extends DefVariable
{
} // DefCollectionTypeVariable
