/**
 * generated by Xtext 2.10.0
 */
package uo.diesels.model.persistenceDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method Simple Return</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uo.diesels.model.persistenceDsl.MethodSimpleReturn#getReturnType <em>Return Type</em>}</li>
 *   <li>{@link uo.diesels.model.persistenceDsl.MethodSimpleReturn#getNullable <em>Nullable</em>}</li>
 * </ul>
 *
 * @see uo.diesels.model.persistenceDsl.PersistenceDslPackage#getMethodSimpleReturn()
 * @model
 * @generated
 */
public interface MethodSimpleReturn extends FinderMethod
{
  /**
   * Returns the value of the '<em><b>Return Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Return Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Return Type</em>' attribute.
   * @see #setReturnType(String)
   * @see uo.diesels.model.persistenceDsl.PersistenceDslPackage#getMethodSimpleReturn_ReturnType()
   * @model
   * @generated
   */
  String getReturnType();

  /**
   * Sets the value of the '{@link uo.diesels.model.persistenceDsl.MethodSimpleReturn#getReturnType <em>Return Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Return Type</em>' attribute.
   * @see #getReturnType()
   * @generated
   */
  void setReturnType(String value);

  /**
   * Returns the value of the '<em><b>Nullable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nullable</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nullable</em>' attribute.
   * @see #setNullable(String)
   * @see uo.diesels.model.persistenceDsl.PersistenceDslPackage#getMethodSimpleReturn_Nullable()
   * @model
   * @generated
   */
  String getNullable();

  /**
   * Sets the value of the '{@link uo.diesels.model.persistenceDsl.MethodSimpleReturn#getNullable <em>Nullable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nullable</em>' attribute.
   * @see #getNullable()
   * @generated
   */
  void setNullable(String value);

} // MethodSimpleReturn
