/**
 * generated by Xtext 2.10.0
 */
package uo.diesels.model.persistenceDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uo.diesels.model.persistenceDsl.Model#getFinder <em>Finder</em>}</li>
 * </ul>
 *
 * @see uo.diesels.model.persistenceDsl.PersistenceDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Finder</b></em>' containment reference list.
   * The list contents are of type {@link uo.diesels.model.persistenceDsl.Finder}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Finder</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Finder</em>' containment reference list.
   * @see uo.diesels.model.persistenceDsl.PersistenceDslPackage#getModel_Finder()
   * @model containment="true"
   * @generated
   */
  EList<Finder> getFinder();

} // Model
