/*
 * generated by Xtext 2.10.0
 */
package uo.diesels.model.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import uo.diesels.model.ui.internal.ModelActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DtoDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ModelActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ModelActivator.getInstance().getInjector(ModelActivator.UO_DIESELS_MODEL_DTODSL);
	}
	
}
