/**
 * generated by Xtext 2.10.0
 */
package uo.diesels.model.persistenceDsl.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import uo.diesels.model.dtoDsl.DtoDslPackage;

import uo.diesels.model.modelDsl.ModelDslPackage;

import uo.diesels.model.persistenceDsl.AllModelTypeCollection;
import uo.diesels.model.persistenceDsl.CollectionReturnType;
import uo.diesels.model.persistenceDsl.DefAllModelTypeCollectionVariable;
import uo.diesels.model.persistenceDsl.DefAllModelTypeVariable;
import uo.diesels.model.persistenceDsl.DefCollectionTypeVariable;
import uo.diesels.model.persistenceDsl.DefSimpleTypeCollectionVariable;
import uo.diesels.model.persistenceDsl.DefSimpleVariable;
import uo.diesels.model.persistenceDsl.DefVariable;
import uo.diesels.model.persistenceDsl.DtoReturnTypeCollection;
import uo.diesels.model.persistenceDsl.EntityReturnTypeCollection;
import uo.diesels.model.persistenceDsl.Finder;
import uo.diesels.model.persistenceDsl.FinderMethod;
import uo.diesels.model.persistenceDsl.MethodCollectionReturn;
import uo.diesels.model.persistenceDsl.MethodDtoReturn;
import uo.diesels.model.persistenceDsl.MethodEntityReturn;
import uo.diesels.model.persistenceDsl.MethodSimpleReturn;
import uo.diesels.model.persistenceDsl.Model;
import uo.diesels.model.persistenceDsl.PersistenceDslFactory;
import uo.diesels.model.persistenceDsl.PersistenceDslPackage;
import uo.diesels.model.persistenceDsl.SimpleReturnTypeCollection;
import uo.diesels.model.persistenceDsl.SimpleTypeCollection;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class PersistenceDslPackageImpl extends EPackageImpl implements PersistenceDslPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass finderEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass finderMethodEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass methodSimpleReturnEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass methodEntityReturnEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass methodDtoReturnEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass methodCollectionReturnEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass collectionReturnTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityReturnTypeCollectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dtoReturnTypeCollectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass simpleReturnTypeCollectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass allModelTypeCollectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass simpleTypeCollectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass defVariableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass defAllModelTypeVariableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass defSimpleVariableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass defCollectionTypeVariableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass defAllModelTypeCollectionVariableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass defSimpleTypeCollectionVariableEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see uo.diesels.model.persistenceDsl.PersistenceDslPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private PersistenceDslPackageImpl()
  {
    super(eNS_URI, PersistenceDslFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link PersistenceDslPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static PersistenceDslPackage init()
  {
    if (isInited) return (PersistenceDslPackage)EPackage.Registry.INSTANCE.getEPackage(PersistenceDslPackage.eNS_URI);

    // Obtain or create and register package
    PersistenceDslPackageImpl thePersistenceDslPackage = (PersistenceDslPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof PersistenceDslPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new PersistenceDslPackageImpl());

    isInited = true;

    // Initialize simple dependencies
    DtoDslPackage.eINSTANCE.eClass();

    // Create package meta-data objects
    thePersistenceDslPackage.createPackageContents();

    // Initialize created meta-data
    thePersistenceDslPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    thePersistenceDslPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(PersistenceDslPackage.eNS_URI, thePersistenceDslPackage);
    return thePersistenceDslPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getModel_Finder()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFinder()
  {
    return finderEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFinder_Name()
  {
    return (EAttribute)finderEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFinder_Methods()
  {
    return (EReference)finderEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFinderMethod()
  {
    return finderMethodEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFinderMethod_Name()
  {
    return (EAttribute)finderMethodEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFinderMethod_Parameters()
  {
    return (EReference)finderMethodEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMethodSimpleReturn()
  {
    return methodSimpleReturnEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMethodSimpleReturn_ReturnType()
  {
    return (EAttribute)methodSimpleReturnEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMethodSimpleReturn_Nullable()
  {
    return (EAttribute)methodSimpleReturnEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMethodEntityReturn()
  {
    return methodEntityReturnEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMethodEntityReturn_ReturnType()
  {
    return (EReference)methodEntityReturnEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMethodEntityReturn_Nullable()
  {
    return (EAttribute)methodEntityReturnEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMethodDtoReturn()
  {
    return methodDtoReturnEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMethodDtoReturn_ReturnType()
  {
    return (EReference)methodDtoReturnEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMethodDtoReturn_Nullable()
  {
    return (EAttribute)methodDtoReturnEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMethodCollectionReturn()
  {
    return methodCollectionReturnEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMethodCollectionReturn_ReturnType()
  {
    return (EReference)methodCollectionReturnEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCollectionReturnType()
  {
    return collectionReturnTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEntityReturnTypeCollection()
  {
    return entityReturnTypeCollectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEntityReturnTypeCollection_Type()
  {
    return (EReference)entityReturnTypeCollectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDtoReturnTypeCollection()
  {
    return dtoReturnTypeCollectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDtoReturnTypeCollection_Type()
  {
    return (EReference)dtoReturnTypeCollectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSimpleReturnTypeCollection()
  {
    return simpleReturnTypeCollectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSimpleReturnTypeCollection_Type()
  {
    return (EAttribute)simpleReturnTypeCollectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAllModelTypeCollection()
  {
    return allModelTypeCollectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAllModelTypeCollection_Collection()
  {
    return (EAttribute)allModelTypeCollectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAllModelTypeCollection_Type()
  {
    return (EReference)allModelTypeCollectionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSimpleTypeCollection()
  {
    return simpleTypeCollectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSimpleTypeCollection_Collection()
  {
    return (EAttribute)simpleTypeCollectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSimpleTypeCollection_Type()
  {
    return (EAttribute)simpleTypeCollectionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDefVariable()
  {
    return defVariableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDefVariable_Name()
  {
    return (EAttribute)defVariableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDefAllModelTypeVariable()
  {
    return defAllModelTypeVariableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDefAllModelTypeVariable_Type()
  {
    return (EReference)defAllModelTypeVariableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDefSimpleVariable()
  {
    return defSimpleVariableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDefSimpleVariable_Type()
  {
    return (EAttribute)defSimpleVariableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDefCollectionTypeVariable()
  {
    return defCollectionTypeVariableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDefAllModelTypeCollectionVariable()
  {
    return defAllModelTypeCollectionVariableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDefAllModelTypeCollectionVariable_Type()
  {
    return (EReference)defAllModelTypeCollectionVariableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDefSimpleTypeCollectionVariable()
  {
    return defSimpleTypeCollectionVariableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDefSimpleTypeCollectionVariable_Type()
  {
    return (EReference)defSimpleTypeCollectionVariableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PersistenceDslFactory getPersistenceDslFactory()
  {
    return (PersistenceDslFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__FINDER);

    finderEClass = createEClass(FINDER);
    createEAttribute(finderEClass, FINDER__NAME);
    createEReference(finderEClass, FINDER__METHODS);

    finderMethodEClass = createEClass(FINDER_METHOD);
    createEAttribute(finderMethodEClass, FINDER_METHOD__NAME);
    createEReference(finderMethodEClass, FINDER_METHOD__PARAMETERS);

    methodSimpleReturnEClass = createEClass(METHOD_SIMPLE_RETURN);
    createEAttribute(methodSimpleReturnEClass, METHOD_SIMPLE_RETURN__RETURN_TYPE);
    createEAttribute(methodSimpleReturnEClass, METHOD_SIMPLE_RETURN__NULLABLE);

    methodEntityReturnEClass = createEClass(METHOD_ENTITY_RETURN);
    createEReference(methodEntityReturnEClass, METHOD_ENTITY_RETURN__RETURN_TYPE);
    createEAttribute(methodEntityReturnEClass, METHOD_ENTITY_RETURN__NULLABLE);

    methodDtoReturnEClass = createEClass(METHOD_DTO_RETURN);
    createEReference(methodDtoReturnEClass, METHOD_DTO_RETURN__RETURN_TYPE);
    createEAttribute(methodDtoReturnEClass, METHOD_DTO_RETURN__NULLABLE);

    methodCollectionReturnEClass = createEClass(METHOD_COLLECTION_RETURN);
    createEReference(methodCollectionReturnEClass, METHOD_COLLECTION_RETURN__RETURN_TYPE);

    collectionReturnTypeEClass = createEClass(COLLECTION_RETURN_TYPE);

    entityReturnTypeCollectionEClass = createEClass(ENTITY_RETURN_TYPE_COLLECTION);
    createEReference(entityReturnTypeCollectionEClass, ENTITY_RETURN_TYPE_COLLECTION__TYPE);

    dtoReturnTypeCollectionEClass = createEClass(DTO_RETURN_TYPE_COLLECTION);
    createEReference(dtoReturnTypeCollectionEClass, DTO_RETURN_TYPE_COLLECTION__TYPE);

    simpleReturnTypeCollectionEClass = createEClass(SIMPLE_RETURN_TYPE_COLLECTION);
    createEAttribute(simpleReturnTypeCollectionEClass, SIMPLE_RETURN_TYPE_COLLECTION__TYPE);

    allModelTypeCollectionEClass = createEClass(ALL_MODEL_TYPE_COLLECTION);
    createEAttribute(allModelTypeCollectionEClass, ALL_MODEL_TYPE_COLLECTION__COLLECTION);
    createEReference(allModelTypeCollectionEClass, ALL_MODEL_TYPE_COLLECTION__TYPE);

    simpleTypeCollectionEClass = createEClass(SIMPLE_TYPE_COLLECTION);
    createEAttribute(simpleTypeCollectionEClass, SIMPLE_TYPE_COLLECTION__COLLECTION);
    createEAttribute(simpleTypeCollectionEClass, SIMPLE_TYPE_COLLECTION__TYPE);

    defVariableEClass = createEClass(DEF_VARIABLE);
    createEAttribute(defVariableEClass, DEF_VARIABLE__NAME);

    defAllModelTypeVariableEClass = createEClass(DEF_ALL_MODEL_TYPE_VARIABLE);
    createEReference(defAllModelTypeVariableEClass, DEF_ALL_MODEL_TYPE_VARIABLE__TYPE);

    defSimpleVariableEClass = createEClass(DEF_SIMPLE_VARIABLE);
    createEAttribute(defSimpleVariableEClass, DEF_SIMPLE_VARIABLE__TYPE);

    defCollectionTypeVariableEClass = createEClass(DEF_COLLECTION_TYPE_VARIABLE);

    defAllModelTypeCollectionVariableEClass = createEClass(DEF_ALL_MODEL_TYPE_COLLECTION_VARIABLE);
    createEReference(defAllModelTypeCollectionVariableEClass, DEF_ALL_MODEL_TYPE_COLLECTION_VARIABLE__TYPE);

    defSimpleTypeCollectionVariableEClass = createEClass(DEF_SIMPLE_TYPE_COLLECTION_VARIABLE);
    createEReference(defSimpleTypeCollectionVariableEClass, DEF_SIMPLE_TYPE_COLLECTION_VARIABLE__TYPE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Obtain other dependent packages
    ModelDslPackage theModelDslPackage = (ModelDslPackage)EPackage.Registry.INSTANCE.getEPackage(ModelDslPackage.eNS_URI);
    DtoDslPackage theDtoDslPackage = (DtoDslPackage)EPackage.Registry.INSTANCE.getEPackage(DtoDslPackage.eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    methodSimpleReturnEClass.getESuperTypes().add(this.getFinderMethod());
    methodEntityReturnEClass.getESuperTypes().add(this.getFinderMethod());
    methodDtoReturnEClass.getESuperTypes().add(this.getFinderMethod());
    methodCollectionReturnEClass.getESuperTypes().add(this.getFinderMethod());
    entityReturnTypeCollectionEClass.getESuperTypes().add(this.getCollectionReturnType());
    dtoReturnTypeCollectionEClass.getESuperTypes().add(this.getCollectionReturnType());
    simpleReturnTypeCollectionEClass.getESuperTypes().add(this.getCollectionReturnType());
    defAllModelTypeVariableEClass.getESuperTypes().add(this.getDefVariable());
    defSimpleVariableEClass.getESuperTypes().add(this.getDefVariable());
    defCollectionTypeVariableEClass.getESuperTypes().add(this.getDefVariable());
    defAllModelTypeCollectionVariableEClass.getESuperTypes().add(this.getDefCollectionTypeVariable());
    defSimpleTypeCollectionVariableEClass.getESuperTypes().add(this.getDefCollectionTypeVariable());

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Finder(), this.getFinder(), null, "finder", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(finderEClass, Finder.class, "Finder", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFinder_Name(), ecorePackage.getEString(), "name", null, 0, 1, Finder.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFinder_Methods(), this.getFinderMethod(), null, "methods", null, 0, -1, Finder.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(finderMethodEClass, FinderMethod.class, "FinderMethod", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFinderMethod_Name(), ecorePackage.getEString(), "name", null, 0, 1, FinderMethod.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFinderMethod_Parameters(), this.getDefVariable(), null, "parameters", null, 0, -1, FinderMethod.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(methodSimpleReturnEClass, MethodSimpleReturn.class, "MethodSimpleReturn", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMethodSimpleReturn_ReturnType(), ecorePackage.getEString(), "returnType", null, 0, 1, MethodSimpleReturn.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMethodSimpleReturn_Nullable(), ecorePackage.getEString(), "nullable", null, 0, 1, MethodSimpleReturn.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(methodEntityReturnEClass, MethodEntityReturn.class, "MethodEntityReturn", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMethodEntityReturn_ReturnType(), theModelDslPackage.getEntity(), null, "returnType", null, 0, 1, MethodEntityReturn.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMethodEntityReturn_Nullable(), ecorePackage.getEString(), "nullable", null, 0, 1, MethodEntityReturn.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(methodDtoReturnEClass, MethodDtoReturn.class, "MethodDtoReturn", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMethodDtoReturn_ReturnType(), theDtoDslPackage.getDto(), null, "returnType", null, 0, 1, MethodDtoReturn.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMethodDtoReturn_Nullable(), ecorePackage.getEString(), "nullable", null, 0, 1, MethodDtoReturn.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(methodCollectionReturnEClass, MethodCollectionReturn.class, "MethodCollectionReturn", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMethodCollectionReturn_ReturnType(), this.getCollectionReturnType(), null, "returnType", null, 0, 1, MethodCollectionReturn.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(collectionReturnTypeEClass, CollectionReturnType.class, "CollectionReturnType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(entityReturnTypeCollectionEClass, EntityReturnTypeCollection.class, "EntityReturnTypeCollection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEntityReturnTypeCollection_Type(), theModelDslPackage.getEntity(), null, "type", null, 0, 1, EntityReturnTypeCollection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dtoReturnTypeCollectionEClass, DtoReturnTypeCollection.class, "DtoReturnTypeCollection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDtoReturnTypeCollection_Type(), theDtoDslPackage.getDto(), null, "type", null, 0, 1, DtoReturnTypeCollection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(simpleReturnTypeCollectionEClass, SimpleReturnTypeCollection.class, "SimpleReturnTypeCollection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSimpleReturnTypeCollection_Type(), ecorePackage.getEString(), "type", null, 0, 1, SimpleReturnTypeCollection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(allModelTypeCollectionEClass, AllModelTypeCollection.class, "AllModelTypeCollection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAllModelTypeCollection_Collection(), ecorePackage.getEString(), "collection", null, 0, 1, AllModelTypeCollection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAllModelTypeCollection_Type(), theModelDslPackage.getAllModelType(), null, "type", null, 0, 1, AllModelTypeCollection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(simpleTypeCollectionEClass, SimpleTypeCollection.class, "SimpleTypeCollection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSimpleTypeCollection_Collection(), ecorePackage.getEString(), "collection", null, 0, 1, SimpleTypeCollection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSimpleTypeCollection_Type(), ecorePackage.getEString(), "type", null, 0, 1, SimpleTypeCollection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(defVariableEClass, DefVariable.class, "DefVariable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDefVariable_Name(), ecorePackage.getEString(), "name", null, 0, 1, DefVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(defAllModelTypeVariableEClass, DefAllModelTypeVariable.class, "DefAllModelTypeVariable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDefAllModelTypeVariable_Type(), theModelDslPackage.getAllModelType(), null, "type", null, 0, 1, DefAllModelTypeVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(defSimpleVariableEClass, DefSimpleVariable.class, "DefSimpleVariable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDefSimpleVariable_Type(), ecorePackage.getEString(), "type", null, 0, 1, DefSimpleVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(defCollectionTypeVariableEClass, DefCollectionTypeVariable.class, "DefCollectionTypeVariable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(defAllModelTypeCollectionVariableEClass, DefAllModelTypeCollectionVariable.class, "DefAllModelTypeCollectionVariable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDefAllModelTypeCollectionVariable_Type(), this.getAllModelTypeCollection(), null, "type", null, 0, 1, DefAllModelTypeCollectionVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(defSimpleTypeCollectionVariableEClass, DefSimpleTypeCollectionVariable.class, "DefSimpleTypeCollectionVariable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDefSimpleTypeCollectionVariable_Type(), this.getSimpleTypeCollection(), null, "type", null, 0, 1, DefSimpleTypeCollectionVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //PersistenceDslPackageImpl
