/*
 * generated by Xtext 2.9.0
 */
package uo.diesels.model.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class PersistenceDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.Model");
		private final Assignment cFinderAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cFinderFinderParserRuleCall_0 = (RuleCall)cFinderAssignment.eContents().get(0);
		
		//Model:
		//	finder+=Finder*;
		@Override public ParserRule getRule() { return rule; }
		
		//finder+=Finder*
		public Assignment getFinderAssignment() { return cFinderAssignment; }
		
		//Finder
		public RuleCall getFinderFinderParserRuleCall_0() { return cFinderFinderParserRuleCall_0; }
	}
	public class FinderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.Finder");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFinderKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cMethodsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMethodsFinderMethodParserRuleCall_3_0 = (RuleCall)cMethodsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Finder:
		//	'Finder' name=ID '{'
		//	methods+=FinderMethod+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Finder' name=ID '{' methods+=FinderMethod+ '}'
		public Group getGroup() { return cGroup; }
		
		//'Finder'
		public Keyword getFinderKeyword_0() { return cFinderKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//methods+=FinderMethod+
		public Assignment getMethodsAssignment_3() { return cMethodsAssignment_3; }
		
		//FinderMethod
		public RuleCall getMethodsFinderMethodParserRuleCall_3_0() { return cMethodsFinderMethodParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class FinderMethodElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.FinderMethod");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMethodEntityReturnParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cMethodDtoReturnParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cMethodSimpleReturnParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cMethodCollectionReturnParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//FinderMethod:
		//	MethodEntityReturn | MethodDtoReturn | MethodSimpleReturn | MethodCollectionReturn;
		@Override public ParserRule getRule() { return rule; }
		
		//MethodEntityReturn | MethodDtoReturn | MethodSimpleReturn | MethodCollectionReturn
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//MethodEntityReturn
		public RuleCall getMethodEntityReturnParserRuleCall_0() { return cMethodEntityReturnParserRuleCall_0; }
		
		//MethodDtoReturn
		public RuleCall getMethodDtoReturnParserRuleCall_1() { return cMethodDtoReturnParserRuleCall_1; }
		
		//MethodSimpleReturn
		public RuleCall getMethodSimpleReturnParserRuleCall_2() { return cMethodSimpleReturnParserRuleCall_2; }
		
		//MethodCollectionReturn
		public RuleCall getMethodCollectionReturnParserRuleCall_3() { return cMethodCollectionReturnParserRuleCall_3; }
	}
	public class MethodSimpleReturnElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.MethodSimpleReturn");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cReturnTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cReturnTypeTypeParserRuleCall_0_0 = (RuleCall)cReturnTypeAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Assignment cParametersAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final RuleCall cParametersDefVariableParserRuleCall_3_0_0 = (RuleCall)cParametersAssignment_3_0.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cGroup_3.eContents().get(1);
		private final Keyword cCommaKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Assignment cParametersAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cParametersDefVariableParserRuleCall_3_1_1_0 = (RuleCall)cParametersAssignment_3_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cNullableAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final Keyword cNullableNonNullKeyword_5_0 = (Keyword)cNullableAssignment_5.eContents().get(0);
		
		//MethodSimpleReturn:
		//	returnType=Type name=ID '(' (parameters+=DefVariable (',' parameters+=DefVariable)*)? ')' nullable="non-null"?;
		@Override public ParserRule getRule() { return rule; }
		
		//returnType=Type name=ID '(' (parameters+=DefVariable (',' parameters+=DefVariable)*)? ')' nullable="non-null"?
		public Group getGroup() { return cGroup; }
		
		//returnType=Type
		public Assignment getReturnTypeAssignment_0() { return cReturnTypeAssignment_0; }
		
		//Type
		public RuleCall getReturnTypeTypeParserRuleCall_0_0() { return cReturnTypeTypeParserRuleCall_0_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//(parameters+=DefVariable (',' parameters+=DefVariable)*)?
		public Group getGroup_3() { return cGroup_3; }
		
		//parameters+=DefVariable
		public Assignment getParametersAssignment_3_0() { return cParametersAssignment_3_0; }
		
		//DefVariable
		public RuleCall getParametersDefVariableParserRuleCall_3_0_0() { return cParametersDefVariableParserRuleCall_3_0_0; }
		
		//(',' parameters+=DefVariable)*
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//','
		public Keyword getCommaKeyword_3_1_0() { return cCommaKeyword_3_1_0; }
		
		//parameters+=DefVariable
		public Assignment getParametersAssignment_3_1_1() { return cParametersAssignment_3_1_1; }
		
		//DefVariable
		public RuleCall getParametersDefVariableParserRuleCall_3_1_1_0() { return cParametersDefVariableParserRuleCall_3_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
		
		//nullable="non-null"?
		public Assignment getNullableAssignment_5() { return cNullableAssignment_5; }
		
		//"non-null"
		public Keyword getNullableNonNullKeyword_5_0() { return cNullableNonNullKeyword_5_0; }
	}
	public class MethodEntityReturnElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.MethodEntityReturn");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cReturnTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cReturnTypeEntityCrossReference_0_0 = (CrossReference)cReturnTypeAssignment_0.eContents().get(0);
		private final RuleCall cReturnTypeEntityIDTerminalRuleCall_0_0_1 = (RuleCall)cReturnTypeEntityCrossReference_0_0.eContents().get(1);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Assignment cParametersAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final RuleCall cParametersDefVariableParserRuleCall_3_0_0 = (RuleCall)cParametersAssignment_3_0.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cGroup_3.eContents().get(1);
		private final Keyword cCommaKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Assignment cParametersAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cParametersDefVariableParserRuleCall_3_1_1_0 = (RuleCall)cParametersAssignment_3_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cNullableAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final Keyword cNullableNonNullKeyword_5_0 = (Keyword)cNullableAssignment_5.eContents().get(0);
		
		//MethodEntityReturn:
		//	returnType=[Model::Entity] name=ID '(' (parameters+=DefVariable (',' parameters+=DefVariable)*)? ')'
		//	nullable="non-null"?;
		@Override public ParserRule getRule() { return rule; }
		
		//returnType=[Model::Entity] name=ID '(' (parameters+=DefVariable (',' parameters+=DefVariable)*)? ')'
		//nullable="non-null"?
		public Group getGroup() { return cGroup; }
		
		//returnType=[Model::Entity]
		public Assignment getReturnTypeAssignment_0() { return cReturnTypeAssignment_0; }
		
		//[Model::Entity]
		public CrossReference getReturnTypeEntityCrossReference_0_0() { return cReturnTypeEntityCrossReference_0_0; }
		
		//ID
		public RuleCall getReturnTypeEntityIDTerminalRuleCall_0_0_1() { return cReturnTypeEntityIDTerminalRuleCall_0_0_1; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//(parameters+=DefVariable (',' parameters+=DefVariable)*)?
		public Group getGroup_3() { return cGroup_3; }
		
		//parameters+=DefVariable
		public Assignment getParametersAssignment_3_0() { return cParametersAssignment_3_0; }
		
		//DefVariable
		public RuleCall getParametersDefVariableParserRuleCall_3_0_0() { return cParametersDefVariableParserRuleCall_3_0_0; }
		
		//(',' parameters+=DefVariable)*
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//','
		public Keyword getCommaKeyword_3_1_0() { return cCommaKeyword_3_1_0; }
		
		//parameters+=DefVariable
		public Assignment getParametersAssignment_3_1_1() { return cParametersAssignment_3_1_1; }
		
		//DefVariable
		public RuleCall getParametersDefVariableParserRuleCall_3_1_1_0() { return cParametersDefVariableParserRuleCall_3_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
		
		//nullable="non-null"?
		public Assignment getNullableAssignment_5() { return cNullableAssignment_5; }
		
		//"non-null"
		public Keyword getNullableNonNullKeyword_5_0() { return cNullableNonNullKeyword_5_0; }
	}
	public class MethodDtoReturnElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.MethodDtoReturn");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNumberSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cReturnTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cReturnTypeDtoCrossReference_1_0 = (CrossReference)cReturnTypeAssignment_1.eContents().get(0);
		private final RuleCall cReturnTypeDtoIDTerminalRuleCall_1_0_1 = (RuleCall)cReturnTypeDtoCrossReference_1_0.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cParametersAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cParametersDefVariableParserRuleCall_4_0_0 = (RuleCall)cParametersAssignment_4_0.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cGroup_4.eContents().get(1);
		private final Keyword cCommaKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Assignment cParametersAssignment_4_1_1 = (Assignment)cGroup_4_1.eContents().get(1);
		private final RuleCall cParametersDefVariableParserRuleCall_4_1_1_0 = (RuleCall)cParametersAssignment_4_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cNullableAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final Keyword cNullableNonNullKeyword_6_0 = (Keyword)cNullableAssignment_6.eContents().get(0);
		
		//MethodDtoReturn:
		//	'#' returnType=[Dto::Dto] name=ID '(' (parameters+=DefVariable (',' parameters+=DefVariable)*)? ')'
		//	nullable="non-null"?;
		@Override public ParserRule getRule() { return rule; }
		
		//'#' returnType=[Dto::Dto] name=ID '(' (parameters+=DefVariable (',' parameters+=DefVariable)*)? ')' nullable="non-null"?
		public Group getGroup() { return cGroup; }
		
		//'#'
		public Keyword getNumberSignKeyword_0() { return cNumberSignKeyword_0; }
		
		//returnType=[Dto::Dto]
		public Assignment getReturnTypeAssignment_1() { return cReturnTypeAssignment_1; }
		
		//[Dto::Dto]
		public CrossReference getReturnTypeDtoCrossReference_1_0() { return cReturnTypeDtoCrossReference_1_0; }
		
		//ID
		public RuleCall getReturnTypeDtoIDTerminalRuleCall_1_0_1() { return cReturnTypeDtoIDTerminalRuleCall_1_0_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//(parameters+=DefVariable (',' parameters+=DefVariable)*)?
		public Group getGroup_4() { return cGroup_4; }
		
		//parameters+=DefVariable
		public Assignment getParametersAssignment_4_0() { return cParametersAssignment_4_0; }
		
		//DefVariable
		public RuleCall getParametersDefVariableParserRuleCall_4_0_0() { return cParametersDefVariableParserRuleCall_4_0_0; }
		
		//(',' parameters+=DefVariable)*
		public Group getGroup_4_1() { return cGroup_4_1; }
		
		//','
		public Keyword getCommaKeyword_4_1_0() { return cCommaKeyword_4_1_0; }
		
		//parameters+=DefVariable
		public Assignment getParametersAssignment_4_1_1() { return cParametersAssignment_4_1_1; }
		
		//DefVariable
		public RuleCall getParametersDefVariableParserRuleCall_4_1_1_0() { return cParametersDefVariableParserRuleCall_4_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
		
		//nullable="non-null"?
		public Assignment getNullableAssignment_6() { return cNullableAssignment_6; }
		
		//"non-null"
		public Keyword getNullableNonNullKeyword_6_0() { return cNullableNonNullKeyword_6_0; }
	}
	public class MethodCollectionReturnElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.MethodCollectionReturn");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cReturnTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cReturnTypeCollectionReturnTypeParserRuleCall_0_0 = (RuleCall)cReturnTypeAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Assignment cParametersAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final RuleCall cParametersDefVariableParserRuleCall_3_0_0 = (RuleCall)cParametersAssignment_3_0.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cGroup_3.eContents().get(1);
		private final Keyword cCommaKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Assignment cParametersAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cParametersDefVariableParserRuleCall_3_1_1_0 = (RuleCall)cParametersAssignment_3_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//MethodCollectionReturn:
		//	returnType=CollectionReturnType name=ID '(' (parameters+=DefVariable (',' parameters+=DefVariable)*)? ')';
		@Override public ParserRule getRule() { return rule; }
		
		//returnType=CollectionReturnType name=ID '(' (parameters+=DefVariable (',' parameters+=DefVariable)*)? ')'
		public Group getGroup() { return cGroup; }
		
		//returnType=CollectionReturnType
		public Assignment getReturnTypeAssignment_0() { return cReturnTypeAssignment_0; }
		
		//CollectionReturnType
		public RuleCall getReturnTypeCollectionReturnTypeParserRuleCall_0_0() { return cReturnTypeCollectionReturnTypeParserRuleCall_0_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//(parameters+=DefVariable (',' parameters+=DefVariable)*)?
		public Group getGroup_3() { return cGroup_3; }
		
		//parameters+=DefVariable
		public Assignment getParametersAssignment_3_0() { return cParametersAssignment_3_0; }
		
		//DefVariable
		public RuleCall getParametersDefVariableParserRuleCall_3_0_0() { return cParametersDefVariableParserRuleCall_3_0_0; }
		
		//(',' parameters+=DefVariable)*
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//','
		public Keyword getCommaKeyword_3_1_0() { return cCommaKeyword_3_1_0; }
		
		//parameters+=DefVariable
		public Assignment getParametersAssignment_3_1_1() { return cParametersAssignment_3_1_1; }
		
		//DefVariable
		public RuleCall getParametersDefVariableParserRuleCall_3_1_1_0() { return cParametersDefVariableParserRuleCall_3_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class CollectionReturnTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.CollectionReturnType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cEntityReturnTypeCollectionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDtoReturnTypeCollectionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cSimpleReturnTypeCollectionParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//// Tipos de colección
		//CollectionReturnType:
		//	EntityReturnTypeCollection | DtoReturnTypeCollection | SimpleReturnTypeCollection;
		@Override public ParserRule getRule() { return rule; }
		
		//EntityReturnTypeCollection | DtoReturnTypeCollection | SimpleReturnTypeCollection
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//EntityReturnTypeCollection
		public RuleCall getEntityReturnTypeCollectionParserRuleCall_0() { return cEntityReturnTypeCollectionParserRuleCall_0; }
		
		//DtoReturnTypeCollection
		public RuleCall getDtoReturnTypeCollectionParserRuleCall_1() { return cDtoReturnTypeCollectionParserRuleCall_1; }
		
		//SimpleReturnTypeCollection
		public RuleCall getSimpleReturnTypeCollectionParserRuleCall_2() { return cSimpleReturnTypeCollectionParserRuleCall_2; }
	}
	public class EntityReturnTypeCollectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.EntityReturnTypeCollection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cLISTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cLessThanSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cTypeEntityCrossReference_2_0 = (CrossReference)cTypeAssignment_2.eContents().get(0);
		private final RuleCall cTypeEntityIDTerminalRuleCall_2_0_1 = (RuleCall)cTypeEntityCrossReference_2_0.eContents().get(1);
		private final Keyword cGreaterThanSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//EntityReturnTypeCollection:
		//	LIST '<' type=[Model::Entity] '>';
		@Override public ParserRule getRule() { return rule; }
		
		//LIST '<' type=[Model::Entity] '>'
		public Group getGroup() { return cGroup; }
		
		//LIST
		public RuleCall getLISTTerminalRuleCall_0() { return cLISTTerminalRuleCall_0; }
		
		//'<'
		public Keyword getLessThanSignKeyword_1() { return cLessThanSignKeyword_1; }
		
		//type=[Model::Entity]
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//[Model::Entity]
		public CrossReference getTypeEntityCrossReference_2_0() { return cTypeEntityCrossReference_2_0; }
		
		//ID
		public RuleCall getTypeEntityIDTerminalRuleCall_2_0_1() { return cTypeEntityIDTerminalRuleCall_2_0_1; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_3() { return cGreaterThanSignKeyword_3; }
	}
	public class DtoReturnTypeCollectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.DtoReturnTypeCollection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cLISTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cLessThanSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cNumberSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cTypeDtoCrossReference_3_0 = (CrossReference)cTypeAssignment_3.eContents().get(0);
		private final RuleCall cTypeDtoIDTerminalRuleCall_3_0_1 = (RuleCall)cTypeDtoCrossReference_3_0.eContents().get(1);
		private final Keyword cGreaterThanSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//DtoReturnTypeCollection:
		//	LIST '<' '#' type=[Dto::Dto] '>';
		@Override public ParserRule getRule() { return rule; }
		
		//LIST '<' '#' type=[Dto::Dto] '>'
		public Group getGroup() { return cGroup; }
		
		//LIST
		public RuleCall getLISTTerminalRuleCall_0() { return cLISTTerminalRuleCall_0; }
		
		//'<'
		public Keyword getLessThanSignKeyword_1() { return cLessThanSignKeyword_1; }
		
		//'#'
		public Keyword getNumberSignKeyword_2() { return cNumberSignKeyword_2; }
		
		//type=[Dto::Dto]
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }
		
		//[Dto::Dto]
		public CrossReference getTypeDtoCrossReference_3_0() { return cTypeDtoCrossReference_3_0; }
		
		//ID
		public RuleCall getTypeDtoIDTerminalRuleCall_3_0_1() { return cTypeDtoIDTerminalRuleCall_3_0_1; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_4() { return cGreaterThanSignKeyword_4; }
	}
	public class SimpleReturnTypeCollectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.SimpleReturnTypeCollection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cLISTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cLessThanSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeTypeParserRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//SimpleReturnTypeCollection:
		//	LIST '<' type=Type '>';
		@Override public ParserRule getRule() { return rule; }
		
		//LIST '<' type=Type '>'
		public Group getGroup() { return cGroup; }
		
		//LIST
		public RuleCall getLISTTerminalRuleCall_0() { return cLISTTerminalRuleCall_0; }
		
		//'<'
		public Keyword getLessThanSignKeyword_1() { return cLessThanSignKeyword_1; }
		
		//type=Type
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//Type
		public RuleCall getTypeTypeParserRuleCall_2_0() { return cTypeTypeParserRuleCall_2_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_3() { return cGreaterThanSignKeyword_3; }
	}
	public class AllModelTypeCollectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.AllModelTypeCollection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cCollectionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Alternatives cCollectionAlternatives_0_0 = (Alternatives)cCollectionAssignment_0.eContents().get(0);
		private final RuleCall cCollectionLISTTerminalRuleCall_0_0_0 = (RuleCall)cCollectionAlternatives_0_0.eContents().get(0);
		private final RuleCall cCollectionSETTerminalRuleCall_0_0_1 = (RuleCall)cCollectionAlternatives_0_0.eContents().get(1);
		private final Keyword cLessThanSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cTypeAllModelTypeCrossReference_2_0 = (CrossReference)cTypeAssignment_2.eContents().get(0);
		private final RuleCall cTypeAllModelTypeIDTerminalRuleCall_2_0_1 = (RuleCall)cTypeAllModelTypeCrossReference_2_0.eContents().get(1);
		private final Keyword cGreaterThanSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//AllModelTypeCollection:
		//	collection=(LIST | SET) '<' type=[Model::AllModelType] '>';
		@Override public ParserRule getRule() { return rule; }
		
		//collection=(LIST | SET) '<' type=[Model::AllModelType] '>'
		public Group getGroup() { return cGroup; }
		
		//collection=(LIST | SET)
		public Assignment getCollectionAssignment_0() { return cCollectionAssignment_0; }
		
		//(LIST | SET)
		public Alternatives getCollectionAlternatives_0_0() { return cCollectionAlternatives_0_0; }
		
		//LIST
		public RuleCall getCollectionLISTTerminalRuleCall_0_0_0() { return cCollectionLISTTerminalRuleCall_0_0_0; }
		
		//SET
		public RuleCall getCollectionSETTerminalRuleCall_0_0_1() { return cCollectionSETTerminalRuleCall_0_0_1; }
		
		//'<'
		public Keyword getLessThanSignKeyword_1() { return cLessThanSignKeyword_1; }
		
		//type=[Model::AllModelType]
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//[Model::AllModelType]
		public CrossReference getTypeAllModelTypeCrossReference_2_0() { return cTypeAllModelTypeCrossReference_2_0; }
		
		//ID
		public RuleCall getTypeAllModelTypeIDTerminalRuleCall_2_0_1() { return cTypeAllModelTypeIDTerminalRuleCall_2_0_1; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_3() { return cGreaterThanSignKeyword_3; }
	}
	public class SimpleTypeCollectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.SimpleTypeCollection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cCollectionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Alternatives cCollectionAlternatives_0_0 = (Alternatives)cCollectionAssignment_0.eContents().get(0);
		private final RuleCall cCollectionLISTTerminalRuleCall_0_0_0 = (RuleCall)cCollectionAlternatives_0_0.eContents().get(0);
		private final RuleCall cCollectionSETTerminalRuleCall_0_0_1 = (RuleCall)cCollectionAlternatives_0_0.eContents().get(1);
		private final Keyword cLessThanSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeTypeParserRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//SimpleTypeCollection:
		//	collection=(LIST | SET) '<' type=Type '>';
		@Override public ParserRule getRule() { return rule; }
		
		//collection=(LIST | SET) '<' type=Type '>'
		public Group getGroup() { return cGroup; }
		
		//collection=(LIST | SET)
		public Assignment getCollectionAssignment_0() { return cCollectionAssignment_0; }
		
		//(LIST | SET)
		public Alternatives getCollectionAlternatives_0_0() { return cCollectionAlternatives_0_0; }
		
		//LIST
		public RuleCall getCollectionLISTTerminalRuleCall_0_0_0() { return cCollectionLISTTerminalRuleCall_0_0_0; }
		
		//SET
		public RuleCall getCollectionSETTerminalRuleCall_0_0_1() { return cCollectionSETTerminalRuleCall_0_0_1; }
		
		//'<'
		public Keyword getLessThanSignKeyword_1() { return cLessThanSignKeyword_1; }
		
		//type=Type
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//Type
		public RuleCall getTypeTypeParserRuleCall_2_0() { return cTypeTypeParserRuleCall_2_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_3() { return cGreaterThanSignKeyword_3; }
	}
	public class DefVariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.DefVariable");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cDefSimpleVariableParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDefAllModelTypeVariableParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cDefCollectionTypeVariableParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//// Variables soportadas para los métodos
		//DefVariable:
		//	DefSimpleVariable | DefAllModelTypeVariable | DefCollectionTypeVariable;
		@Override public ParserRule getRule() { return rule; }
		
		//DefSimpleVariable | DefAllModelTypeVariable | DefCollectionTypeVariable
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//DefSimpleVariable
		public RuleCall getDefSimpleVariableParserRuleCall_0() { return cDefSimpleVariableParserRuleCall_0; }
		
		//DefAllModelTypeVariable
		public RuleCall getDefAllModelTypeVariableParserRuleCall_1() { return cDefAllModelTypeVariableParserRuleCall_1; }
		
		//DefCollectionTypeVariable
		public RuleCall getDefCollectionTypeVariableParserRuleCall_2() { return cDefCollectionTypeVariableParserRuleCall_2; }
	}
	public class DefAllModelTypeVariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.DefAllModelTypeVariable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cTypeAllModelTypeCrossReference_0_0 = (CrossReference)cTypeAssignment_0.eContents().get(0);
		private final RuleCall cTypeAllModelTypeIDTerminalRuleCall_0_0_1 = (RuleCall)cTypeAllModelTypeCrossReference_0_0.eContents().get(1);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//DefAllModelTypeVariable:
		//	type=[Model::AllModelType] name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//type=[Model::AllModelType] name=ID
		public Group getGroup() { return cGroup; }
		
		//type=[Model::AllModelType]
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//[Model::AllModelType]
		public CrossReference getTypeAllModelTypeCrossReference_0_0() { return cTypeAllModelTypeCrossReference_0_0; }
		
		//ID
		public RuleCall getTypeAllModelTypeIDTerminalRuleCall_0_0_1() { return cTypeAllModelTypeIDTerminalRuleCall_0_0_1; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class DefSimpleVariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.DefSimpleVariable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeTypeParserRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//DefSimpleVariable:
		//	type=Type name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//type=Type name=ID
		public Group getGroup() { return cGroup; }
		
		//type=Type
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//Type
		public RuleCall getTypeTypeParserRuleCall_0_0() { return cTypeTypeParserRuleCall_0_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class DefCollectionTypeVariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.DefCollectionTypeVariable");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cDefAllModelTypeCollectionVariableParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDefSimpleTypeCollectionVariableParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//DefCollectionTypeVariable:
		//	DefAllModelTypeCollectionVariable | DefSimpleTypeCollectionVariable;
		@Override public ParserRule getRule() { return rule; }
		
		//DefAllModelTypeCollectionVariable | DefSimpleTypeCollectionVariable
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//DefAllModelTypeCollectionVariable
		public RuleCall getDefAllModelTypeCollectionVariableParserRuleCall_0() { return cDefAllModelTypeCollectionVariableParserRuleCall_0; }
		
		//DefSimpleTypeCollectionVariable
		public RuleCall getDefSimpleTypeCollectionVariableParserRuleCall_1() { return cDefSimpleTypeCollectionVariableParserRuleCall_1; }
	}
	public class DefAllModelTypeCollectionVariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.DefAllModelTypeCollectionVariable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeAllModelTypeCollectionParserRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//DefAllModelTypeCollectionVariable:
		//	type=AllModelTypeCollection name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//type=AllModelTypeCollection name=ID
		public Group getGroup() { return cGroup; }
		
		//type=AllModelTypeCollection
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//AllModelTypeCollection
		public RuleCall getTypeAllModelTypeCollectionParserRuleCall_0_0() { return cTypeAllModelTypeCollectionParserRuleCall_0_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class DefSimpleTypeCollectionVariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.DefSimpleTypeCollectionVariable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeSimpleTypeCollectionParserRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//DefSimpleTypeCollectionVariable:
		//	type=SimpleTypeCollection name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//type=SimpleTypeCollection name=ID
		public Group getGroup() { return cGroup; }
		
		//type=SimpleTypeCollection
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//SimpleTypeCollection
		public RuleCall getTypeSimpleTypeCollectionParserRuleCall_0_0() { return cTypeSimpleTypeCollectionParserRuleCall_0_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBasicTypeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cComplexTypeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		////Tipos simples (básicos) y complejos (Date) soportados
		//Type:
		//	BasicType | ComplexType;
		@Override public ParserRule getRule() { return rule; }
		
		//BasicType | ComplexType
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//BasicType
		public RuleCall getBasicTypeParserRuleCall_0() { return cBasicTypeParserRuleCall_0; }
		
		//ComplexType
		public RuleCall getComplexTypeParserRuleCall_1() { return cComplexTypeParserRuleCall_1; }
	}
	public class BasicTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.BasicType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTYPE_INTTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTYPE_DOUBLETerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTYPE_FLOATTerminalRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cTYPE_LONGTerminalRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cTYPE_CHARTerminalRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cTYPE_STRINGTerminalRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cTYPE_BOOLEANTerminalRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//BasicType:
		//	TYPE_INT | TYPE_DOUBLE | TYPE_FLOAT | TYPE_LONG | TYPE_CHAR | TYPE_STRING | TYPE_BOOLEAN;
		@Override public ParserRule getRule() { return rule; }
		
		//TYPE_INT | TYPE_DOUBLE | TYPE_FLOAT | TYPE_LONG | TYPE_CHAR | TYPE_STRING | TYPE_BOOLEAN
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TYPE_INT
		public RuleCall getTYPE_INTTerminalRuleCall_0() { return cTYPE_INTTerminalRuleCall_0; }
		
		//TYPE_DOUBLE
		public RuleCall getTYPE_DOUBLETerminalRuleCall_1() { return cTYPE_DOUBLETerminalRuleCall_1; }
		
		//TYPE_FLOAT
		public RuleCall getTYPE_FLOATTerminalRuleCall_2() { return cTYPE_FLOATTerminalRuleCall_2; }
		
		//TYPE_LONG
		public RuleCall getTYPE_LONGTerminalRuleCall_3() { return cTYPE_LONGTerminalRuleCall_3; }
		
		//TYPE_CHAR
		public RuleCall getTYPE_CHARTerminalRuleCall_4() { return cTYPE_CHARTerminalRuleCall_4; }
		
		//TYPE_STRING
		public RuleCall getTYPE_STRINGTerminalRuleCall_5() { return cTYPE_STRINGTerminalRuleCall_5; }
		
		//TYPE_BOOLEAN
		public RuleCall getTYPE_BOOLEANTerminalRuleCall_6() { return cTYPE_BOOLEANTerminalRuleCall_6; }
	}
	public class ComplexTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.ComplexType");
		private final RuleCall cDATETerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//ComplexType:
		//	DATE;
		@Override public ParserRule getRule() { return rule; }
		
		//DATE
		public RuleCall getDATETerminalRuleCall() { return cDATETerminalRuleCall; }
	}
	
	
	private final ModelElements pModel;
	private final FinderElements pFinder;
	private final FinderMethodElements pFinderMethod;
	private final MethodSimpleReturnElements pMethodSimpleReturn;
	private final MethodEntityReturnElements pMethodEntityReturn;
	private final MethodDtoReturnElements pMethodDtoReturn;
	private final MethodCollectionReturnElements pMethodCollectionReturn;
	private final CollectionReturnTypeElements pCollectionReturnType;
	private final EntityReturnTypeCollectionElements pEntityReturnTypeCollection;
	private final DtoReturnTypeCollectionElements pDtoReturnTypeCollection;
	private final SimpleReturnTypeCollectionElements pSimpleReturnTypeCollection;
	private final AllModelTypeCollectionElements pAllModelTypeCollection;
	private final SimpleTypeCollectionElements pSimpleTypeCollection;
	private final DefVariableElements pDefVariable;
	private final DefAllModelTypeVariableElements pDefAllModelTypeVariable;
	private final DefSimpleVariableElements pDefSimpleVariable;
	private final DefCollectionTypeVariableElements pDefCollectionTypeVariable;
	private final DefAllModelTypeCollectionVariableElements pDefAllModelTypeCollectionVariable;
	private final DefSimpleTypeCollectionVariableElements pDefSimpleTypeCollectionVariable;
	private final TypeElements pType;
	private final BasicTypeElements pBasicType;
	private final ComplexTypeElements pComplexType;
	private final TerminalRule tLIST;
	private final TerminalRule tSET;
	private final TerminalRule tDATE;
	private final TerminalRule tTYPE_INT;
	private final TerminalRule tTYPE_LONG;
	private final TerminalRule tTYPE_DOUBLE;
	private final TerminalRule tTYPE_FLOAT;
	private final TerminalRule tTYPE_CHAR;
	private final TerminalRule tTYPE_STRING;
	private final TerminalRule tTYPE_BOOLEAN;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public PersistenceDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pFinder = new FinderElements();
		this.pFinderMethod = new FinderMethodElements();
		this.pMethodSimpleReturn = new MethodSimpleReturnElements();
		this.pMethodEntityReturn = new MethodEntityReturnElements();
		this.pMethodDtoReturn = new MethodDtoReturnElements();
		this.pMethodCollectionReturn = new MethodCollectionReturnElements();
		this.pCollectionReturnType = new CollectionReturnTypeElements();
		this.pEntityReturnTypeCollection = new EntityReturnTypeCollectionElements();
		this.pDtoReturnTypeCollection = new DtoReturnTypeCollectionElements();
		this.pSimpleReturnTypeCollection = new SimpleReturnTypeCollectionElements();
		this.pAllModelTypeCollection = new AllModelTypeCollectionElements();
		this.pSimpleTypeCollection = new SimpleTypeCollectionElements();
		this.pDefVariable = new DefVariableElements();
		this.pDefAllModelTypeVariable = new DefAllModelTypeVariableElements();
		this.pDefSimpleVariable = new DefSimpleVariableElements();
		this.pDefCollectionTypeVariable = new DefCollectionTypeVariableElements();
		this.pDefAllModelTypeCollectionVariable = new DefAllModelTypeCollectionVariableElements();
		this.pDefSimpleTypeCollectionVariable = new DefSimpleTypeCollectionVariableElements();
		this.pType = new TypeElements();
		this.pBasicType = new BasicTypeElements();
		this.pComplexType = new ComplexTypeElements();
		this.tLIST = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.LIST");
		this.tSET = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.SET");
		this.tDATE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.DATE");
		this.tTYPE_INT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.TYPE_INT");
		this.tTYPE_LONG = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.TYPE_LONG");
		this.tTYPE_DOUBLE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.TYPE_DOUBLE");
		this.tTYPE_FLOAT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.TYPE_FLOAT");
		this.tTYPE_CHAR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.TYPE_CHAR");
		this.tTYPE_STRING = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.TYPE_STRING");
		this.tTYPE_BOOLEAN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "uo.diesels.model.PersistenceDsl.TYPE_BOOLEAN");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("uo.diesels.model.PersistenceDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	finder+=Finder*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Finder:
	//	'Finder' name=ID '{'
	//	methods+=FinderMethod+
	//	'}';
	public FinderElements getFinderAccess() {
		return pFinder;
	}
	
	public ParserRule getFinderRule() {
		return getFinderAccess().getRule();
	}
	
	//FinderMethod:
	//	MethodEntityReturn | MethodDtoReturn | MethodSimpleReturn | MethodCollectionReturn;
	public FinderMethodElements getFinderMethodAccess() {
		return pFinderMethod;
	}
	
	public ParserRule getFinderMethodRule() {
		return getFinderMethodAccess().getRule();
	}
	
	//MethodSimpleReturn:
	//	returnType=Type name=ID '(' (parameters+=DefVariable (',' parameters+=DefVariable)*)? ')' nullable="non-null"?;
	public MethodSimpleReturnElements getMethodSimpleReturnAccess() {
		return pMethodSimpleReturn;
	}
	
	public ParserRule getMethodSimpleReturnRule() {
		return getMethodSimpleReturnAccess().getRule();
	}
	
	//MethodEntityReturn:
	//	returnType=[Model::Entity] name=ID '(' (parameters+=DefVariable (',' parameters+=DefVariable)*)? ')'
	//	nullable="non-null"?;
	public MethodEntityReturnElements getMethodEntityReturnAccess() {
		return pMethodEntityReturn;
	}
	
	public ParserRule getMethodEntityReturnRule() {
		return getMethodEntityReturnAccess().getRule();
	}
	
	//MethodDtoReturn:
	//	'#' returnType=[Dto::Dto] name=ID '(' (parameters+=DefVariable (',' parameters+=DefVariable)*)? ')'
	//	nullable="non-null"?;
	public MethodDtoReturnElements getMethodDtoReturnAccess() {
		return pMethodDtoReturn;
	}
	
	public ParserRule getMethodDtoReturnRule() {
		return getMethodDtoReturnAccess().getRule();
	}
	
	//MethodCollectionReturn:
	//	returnType=CollectionReturnType name=ID '(' (parameters+=DefVariable (',' parameters+=DefVariable)*)? ')';
	public MethodCollectionReturnElements getMethodCollectionReturnAccess() {
		return pMethodCollectionReturn;
	}
	
	public ParserRule getMethodCollectionReturnRule() {
		return getMethodCollectionReturnAccess().getRule();
	}
	
	//// Tipos de colección
	//CollectionReturnType:
	//	EntityReturnTypeCollection | DtoReturnTypeCollection | SimpleReturnTypeCollection;
	public CollectionReturnTypeElements getCollectionReturnTypeAccess() {
		return pCollectionReturnType;
	}
	
	public ParserRule getCollectionReturnTypeRule() {
		return getCollectionReturnTypeAccess().getRule();
	}
	
	//EntityReturnTypeCollection:
	//	LIST '<' type=[Model::Entity] '>';
	public EntityReturnTypeCollectionElements getEntityReturnTypeCollectionAccess() {
		return pEntityReturnTypeCollection;
	}
	
	public ParserRule getEntityReturnTypeCollectionRule() {
		return getEntityReturnTypeCollectionAccess().getRule();
	}
	
	//DtoReturnTypeCollection:
	//	LIST '<' '#' type=[Dto::Dto] '>';
	public DtoReturnTypeCollectionElements getDtoReturnTypeCollectionAccess() {
		return pDtoReturnTypeCollection;
	}
	
	public ParserRule getDtoReturnTypeCollectionRule() {
		return getDtoReturnTypeCollectionAccess().getRule();
	}
	
	//SimpleReturnTypeCollection:
	//	LIST '<' type=Type '>';
	public SimpleReturnTypeCollectionElements getSimpleReturnTypeCollectionAccess() {
		return pSimpleReturnTypeCollection;
	}
	
	public ParserRule getSimpleReturnTypeCollectionRule() {
		return getSimpleReturnTypeCollectionAccess().getRule();
	}
	
	//AllModelTypeCollection:
	//	collection=(LIST | SET) '<' type=[Model::AllModelType] '>';
	public AllModelTypeCollectionElements getAllModelTypeCollectionAccess() {
		return pAllModelTypeCollection;
	}
	
	public ParserRule getAllModelTypeCollectionRule() {
		return getAllModelTypeCollectionAccess().getRule();
	}
	
	//SimpleTypeCollection:
	//	collection=(LIST | SET) '<' type=Type '>';
	public SimpleTypeCollectionElements getSimpleTypeCollectionAccess() {
		return pSimpleTypeCollection;
	}
	
	public ParserRule getSimpleTypeCollectionRule() {
		return getSimpleTypeCollectionAccess().getRule();
	}
	
	//// Variables soportadas para los métodos
	//DefVariable:
	//	DefSimpleVariable | DefAllModelTypeVariable | DefCollectionTypeVariable;
	public DefVariableElements getDefVariableAccess() {
		return pDefVariable;
	}
	
	public ParserRule getDefVariableRule() {
		return getDefVariableAccess().getRule();
	}
	
	//DefAllModelTypeVariable:
	//	type=[Model::AllModelType] name=ID;
	public DefAllModelTypeVariableElements getDefAllModelTypeVariableAccess() {
		return pDefAllModelTypeVariable;
	}
	
	public ParserRule getDefAllModelTypeVariableRule() {
		return getDefAllModelTypeVariableAccess().getRule();
	}
	
	//DefSimpleVariable:
	//	type=Type name=ID;
	public DefSimpleVariableElements getDefSimpleVariableAccess() {
		return pDefSimpleVariable;
	}
	
	public ParserRule getDefSimpleVariableRule() {
		return getDefSimpleVariableAccess().getRule();
	}
	
	//DefCollectionTypeVariable:
	//	DefAllModelTypeCollectionVariable | DefSimpleTypeCollectionVariable;
	public DefCollectionTypeVariableElements getDefCollectionTypeVariableAccess() {
		return pDefCollectionTypeVariable;
	}
	
	public ParserRule getDefCollectionTypeVariableRule() {
		return getDefCollectionTypeVariableAccess().getRule();
	}
	
	//DefAllModelTypeCollectionVariable:
	//	type=AllModelTypeCollection name=ID;
	public DefAllModelTypeCollectionVariableElements getDefAllModelTypeCollectionVariableAccess() {
		return pDefAllModelTypeCollectionVariable;
	}
	
	public ParserRule getDefAllModelTypeCollectionVariableRule() {
		return getDefAllModelTypeCollectionVariableAccess().getRule();
	}
	
	//DefSimpleTypeCollectionVariable:
	//	type=SimpleTypeCollection name=ID;
	public DefSimpleTypeCollectionVariableElements getDefSimpleTypeCollectionVariableAccess() {
		return pDefSimpleTypeCollectionVariable;
	}
	
	public ParserRule getDefSimpleTypeCollectionVariableRule() {
		return getDefSimpleTypeCollectionVariableAccess().getRule();
	}
	
	////Tipos simples (básicos) y complejos (Date) soportados
	//Type:
	//	BasicType | ComplexType;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//BasicType:
	//	TYPE_INT | TYPE_DOUBLE | TYPE_FLOAT | TYPE_LONG | TYPE_CHAR | TYPE_STRING | TYPE_BOOLEAN;
	public BasicTypeElements getBasicTypeAccess() {
		return pBasicType;
	}
	
	public ParserRule getBasicTypeRule() {
		return getBasicTypeAccess().getRule();
	}
	
	//ComplexType:
	//	DATE;
	public ComplexTypeElements getComplexTypeAccess() {
		return pComplexType;
	}
	
	public ParserRule getComplexTypeRule() {
		return getComplexTypeAccess().getRule();
	}
	
	//terminal LIST:
	//	'List';
	public TerminalRule getLISTRule() {
		return tLIST;
	}
	
	//terminal SET:
	//	'Set';
	public TerminalRule getSETRule() {
		return tSET;
	}
	
	//terminal DATE:
	//	'Date';
	public TerminalRule getDATERule() {
		return tDATE;
	}
	
	//terminal TYPE_INT:
	//	'Integer';
	public TerminalRule getTYPE_INTRule() {
		return tTYPE_INT;
	}
	
	//terminal TYPE_LONG:
	//	'Long';
	public TerminalRule getTYPE_LONGRule() {
		return tTYPE_LONG;
	}
	
	//terminal TYPE_DOUBLE:
	//	'Double';
	public TerminalRule getTYPE_DOUBLERule() {
		return tTYPE_DOUBLE;
	}
	
	//terminal TYPE_FLOAT:
	//	'Float';
	public TerminalRule getTYPE_FLOATRule() {
		return tTYPE_FLOAT;
	}
	
	//terminal TYPE_CHAR:
	//	'Character';
	public TerminalRule getTYPE_CHARRule() {
		return tTYPE_CHAR;
	}
	
	//terminal TYPE_STRING:
	//	'String';
	public TerminalRule getTYPE_STRINGRule() {
		return tTYPE_STRING;
	}
	
	//terminal TYPE_BOOLEAN:
	//	'Boolean';
	public TerminalRule getTYPE_BOOLEANRule() {
		return tTYPE_BOOLEAN;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
