/**
 * generated by Xtext 2.9.0
 */
package uo.diesels.model.dtoDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import uo.diesels.model.dtoDsl.DefDtoModelTypeCollectionVariable;
import uo.diesels.model.dtoDsl.DtoDslPackage;

import uo.diesels.model.modelDsl.ModelType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Def Dto Model Type Collection Variable</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uo.diesels.model.dtoDsl.impl.DefDtoModelTypeCollectionVariableImpl#getType <em>Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DefDtoModelTypeCollectionVariableImpl extends DefDtoCollectionTypeAttributeImpl implements DefDtoModelTypeCollectionVariable
{
  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected ModelType type;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DefDtoModelTypeCollectionVariableImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DtoDslPackage.Literals.DEF_DTO_MODEL_TYPE_COLLECTION_VARIABLE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ModelType getType()
  {
    if (type != null && type.eIsProxy())
    {
      InternalEObject oldType = (InternalEObject)type;
      type = (ModelType)eResolveProxy(oldType);
      if (type != oldType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, DtoDslPackage.DEF_DTO_MODEL_TYPE_COLLECTION_VARIABLE__TYPE, oldType, type));
      }
    }
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ModelType basicGetType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setType(ModelType newType)
  {
    ModelType oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DtoDslPackage.DEF_DTO_MODEL_TYPE_COLLECTION_VARIABLE__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DtoDslPackage.DEF_DTO_MODEL_TYPE_COLLECTION_VARIABLE__TYPE:
        if (resolve) return getType();
        return basicGetType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DtoDslPackage.DEF_DTO_MODEL_TYPE_COLLECTION_VARIABLE__TYPE:
        setType((ModelType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DtoDslPackage.DEF_DTO_MODEL_TYPE_COLLECTION_VARIABLE__TYPE:
        setType((ModelType)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DtoDslPackage.DEF_DTO_MODEL_TYPE_COLLECTION_VARIABLE__TYPE:
        return type != null;
    }
    return super.eIsSet(featureID);
  }

} //DefDtoModelTypeCollectionVariableImpl
